Repository push-protocol/push-dapp, pull requests merged in 2023-05, with the labels that each got.

#1104 fixed twitter preview
  src/components/chat/w2wChat/chats/Chats.tsx
Labels: bug, Priority 1

#1093 Space preview component
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/chats/MessageWrappers/ReceivedMessageWrapper.tsx
  src/components/space/spaceBox/RequestBox.tsx
  src/components/space/spaceBox/ScheduledSpace.tsx
  src/components/space/spaceNotification/SpaceNotification.tsx
  src/components/space/spaceNotification/index.ts
  src/components/space/spaceReusables/RequestBody.tsx
  src/components/space/spaceReusables/SpaceCard.tsx
  src/components/space/spaceReusables/SpaceMembersIndicator.tsx
  src/components/space/spaceReusables/index.ts
  src/components/space/spaceSidebar/SpaceSidebar.tsx
  src/components/space/spaceSidebar/searchBar/Searchbar.tsx
  src/components/space/spaceSidebar/searchBar/index.tsx
  src/components/space/spaceSidebar/spaceCard/index.tsx
  src/components/space/spaceSidebar/spaceCard/spaceCard.tsx
  src/components/space/spaceSidebar/spaceInbox/spaceInbox.tsx
  src/components/space/spaceSidebar/spaceRequests/SpaceRequestCard.tsx
  src/config/Themization.js
  src/helpers/space/index.ts
  src/helpers/space/spaceUtility.ts
  src/modules/space/SpaceModule.tsx
  src/services/space/spaceList.ts
  src/types/spaces.ts
Labels: Priority 1

#1099 Change video call notification to additionalMeta endpoint
  package.json
  src/components/chat/w2wChat/TypeBar/Typebar.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/video/VideoPlayer.tsx
  src/contexts/VideoCallContext.tsx
  src/helpers/videoCall/sendVideoCallNotification.ts
  src/hooks/useSDKSocket.ts
  src/modules/chat/ChatModule.tsx
  src/sections/video/VideoCallSection.tsx
  src/types/chat.ts
  yarn.lock
Labels: Priority 1

#1122 Case insensative wallet check in chat
  src/components/chat/chatsnap/ChatSnap.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/groupChat/createGroup/AddWalletContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/MemberListContainer.tsx
  src/components/chat/w2wChat/groupChat/groupInfo/ProfileCard.tsx
  src/components/chat/w2wChat/groupChat/groupInfo/groupInfoModalContent.tsx
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  src/contexts/ChatUserContext.tsx
  src/helpers/TimerHelper.ts
  src/helpers/UtilityHelper.ts
  src/helpers/w2w/groupChat.ts
  src/helpers/w2w/index.ts
  src/helpers/w2w/user.ts
  src/hooks/useResolveWeb3Name.ts
  src/modules/chat/ChatModule.tsx
Labels: Priority 1

#1123 fixed send intent and chat sidebar loading
  package.json
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/sections/chat/ChatSidebarSection.tsx
  yarn.lock
Labels: Priority 1

#973 Added dapp changes for polygon zkEVM testnet for dev, staging
  public/svg/PolygonZkEVM.svg
  src/AppLogin.tsx
  src/components/ChainIndicator.tsx
  src/components/ChainsSelect.tsx
  src/components/Dropdown.tsx
  src/components/Faucets.js
  src/components/VerifyAlias.js
  src/components/ViewChannelItem.js
  src/config/config-dev.js
  src/config/config-prod.js
  src/config/config-staging.js
  src/helpers/CaipHelper.ts
  src/helpers/UtilityHelper.ts
  src/structure/Header.tsx
Labels: Priority-2, feature enhancement

#1086 Space widget at bottom
  src/assets/space/check.svg
  src/assets/space/close.svg
  src/components/space/spaceBox/ActiveSpaces.tsx
  src/components/space/spaceBox/ScheduledSpace.tsx
  src/components/space/spaceReusables/SpaceMembersIndicator.tsx
  src/components/space/spaceWidget/SpaceWidget.tsx
  src/components/space/spaceWidget/index.ts
  src/contexts/SpaceGlobalContext.tsx
  src/services/space/spaceList.ts
  src/structure/MasterInterfacePage.tsx
Labels: Priority 1
