Repository push-protocol/push-dapp, pull requests merged in 2023-04, with the labels that each got.

#940 fixed timestamp issue on sidebar
  src/components/chat/chatsnap/ChatSnap.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/helpers/TimerHelper.ts
  yarn.lock
Labels: Priority-2

#1026 Unstoppable Domains reverse address resolution
  package.json
  src/components/Profile.tsx
  src/components/chat/chatsnap/ChatSnap.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/groupChat/createGroup/AddWalletContent.tsx
  src/components/chat/w2wChat/profile/Profile.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  src/config/config-dev.js
  src/config/config-localhost.js
  src/config/config-prod.js
  src/config/config-staging.js
  src/helpers/w2w/udResolver.ts
  src/hooks/useResolveEns.ts
  src/hooks/useResolveWeb3Name.ts
  src/modules/gov/GovModule.tsx
  src/primaries/Profile.tsx
  src/segments/ChatSidebar.tsx
  yarn.lock
Labels: Priority 1

#1056 Video Call UX fix
  src/contexts/VideoCallContext.tsx
Labels: Priority 1

#1050 Fixed ENS bugs and removed indexedDB caching
  src/App.tsx
  src/components/Profile.tsx
  src/components/chat/chatsnap/ChatSnap.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/profile/Profile.tsx
  src/components/chat/w2wChat/w2wIndexeddb.ts
  src/contexts/AppContext.tsx
  src/contexts/ChatUserContext.tsx
  src/helpers/TimerHelper.ts
  src/helpers/UtilityHelper.ts
  src/hooks/useResolveWeb3Name.ts
  src/modules/chat/ChatModule.tsx
  src/modules/gov/GovModule.tsx
  src/primaries/Profile.tsx
  src/types/context.ts
Labels: Priority 1

#1031 Add the steps to install this Project in Readme.md
  README.md
Labels: Priority-2

#738 Minor CSS fixes in Chats component
  src/components/chat/w2wChat/chats/Chats.tsx
Labels: Priority-3
