Repository push-protocol/push-dapp, pull requests merged in 2023-02, with the labels that each got.

#733 Fixed Goerli ENS resolving issues on dev and staging
  package.json
  src/components/chat/w2wChat/profile/Profile.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  src/helpers/w2w/user.ts
  src/hooks/useResolveEns.ts
Labels: Priority-2

#676 674 convert context folder files to typescript
  src/components/chat/w2wChat/ProfileSection/Profile.css
  src/components/chat/w2wChat/ProfileSection/Profile.tsx
  src/components/chat/w2wChat/ProfileSection/helpers.ts
  src/components/chat/w2wChat/ProfileSection/styles.ts
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/contexts/NavigationContext.tsx
  src/contexts/NotificationContext.tsx
  src/contexts/VideoCallContext.js
  src/contexts/VideoCallContext.tsx
  src/sections/chat/ChatSidebarSection.tsx
Labels: Priority-2

#721 Add time bound fields in create channel flow
  public/svg/ExpiredTimer.svg
  public/svg/ExpiresTimer.svg
  src/components/ChannelDetails.js
  src/components/ChannelInfo.tsx
  src/components/CreateChannel.js
  src/components/NewTag.tsx
  src/components/reusables/toggle/Toggle.tsx
  src/components/reusables/tooltip/Tooltip.tsx
  src/config/Themization.js
  src/helpers/TimerHelper.ts
  src/helpers/UtilityHelper.ts
  src/segments/ChannelOwnerDashboard.tsx
Labels: enhancement, Priority 1

#737 Make the entire entry of chain switcher as clickable
  src/components/Dropdown.tsx
Labels: Priority-2

#742 Create group option
  src/assets/chat/group-chat/creategroup.svg
  src/assets/chat/group-chat/creategroupfill.svg
  src/components/chat/w2wChat/intentFeed/IntentFeed.tsx
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  src/helpers/StyleHelper.ts
  src/sections/chat/ChatSidebarSection.tsx
Labels: enhancement, Priority 1

#751 added sdk functions for send, start and approve intent
  package.json
  src/api/w2w.ts
  src/components/chat/w2wChat/TypeBar/Typebar.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/helpers/UtilityHelper.ts
Labels: Priority 1
