Repository push-protocol/push-dapp, pull requests merged in 2023-03, with the labels that each got.

#691 Fix create channel flow to handle user reject transaction
  package.json
  src/components/CreateChannel.js
Labels: Priority-2

#811 Add and Remove admin
  src/components/chat/w2wChat/TypeBar/Typebar.tsx
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/chats/MessageWrappers/ReceivedMessageWrapper.tsx
  src/components/chat/w2wChat/groupChat/createGroup/AddWalletContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/CreateGroupModalContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/GroupDetailsContent.tsx
  src/components/chat/w2wChat/groupChat/groupInfo/ProfileCard.tsx
  src/components/chat/w2wChat/groupChat/groupInfo/groupInfoModalContent.tsx
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  src/helpers/w2w/groupChat.ts
  src/helpers/w2w/index.ts
  src/helpers/w2w/user.ts
  src/hooks/useModalBlur.tsx
  src/modules/chat/ChatModule.tsx
  src/sections/chat/ChatSidebarSection.tsx
Labels: Priority 1

#897 Edit channel UI fixes
  src/components/ChainsSelect.tsx
  src/components/ChannelInfo.tsx
  src/components/VerifiedTooltipContent.tsx
  src/components/ViewChannelItem.js
  src/components/reusables/tooltip/Tooltip.tsx
  src/modules/editChannel/uploadLogoModal.tsx
  src/segments/ViewChannels.tsx
Labels: Priority 1

#697 Resolved most of the warnings/errors on console
  src/components/AllNFTsV2.js
  src/components/NavigationButton.js
  src/components/SendNotifications.tsx
  src/components/chat/w2wChat/messageFeed/MessageFeed.tsx
  src/components/reusables/loaders/LoaderSpinner.tsx
  src/segments/ViewChannels.tsx
Labels: Priority-2

#922 Add more members in group chat
  src/assets/chat/group-chat/adddark.svg
  src/assets/chat/group-chat/addlight.svg
  src/assets/chat/group-chat/more.svg
  src/assets/chat/group-chat/moredark.svg
  src/components/chat/w2wChat/chatBox/ChatBox.tsx
  src/components/chat/w2wChat/chats/Chats.tsx
  src/components/chat/w2wChat/groupChat/createGroup/AddWalletContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/CreateGroupModalContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/GroupDetailsContent.tsx
  src/components/chat/w2wChat/groupChat/createGroup/GroupModalHeader.tsx
  src/components/chat/w2wChat/groupChat/createGroup/MemberListContainer.tsx
  src/components/chat/w2wChat/groupChat/groupInfo/groupInfoModalContent.tsx
  src/helpers/w2w/groupChat.ts
  src/primaries/SharedModalComponents/ModalConfirmButton.tsx
Labels: Priority 1

#951 fixed padding issue of timebound channel tooltip
  src/components/ChannelInfo.tsx
Labels: enhancement, Priority-2

#934 Added loader when searching address and ens name
  src/components/chat/w2wChat/groupChat/createGroup/AddWalletContent.tsx
  src/components/chat/w2wChat/searchBar/SearchBar.tsx
  yarn.lock
Labels: Priority-2

#979 Added chat local context in chat module
  src/contexts/ChatLocalContextNew.tsx
  src/modules/chat/ChatModuleNew.tsx
Labels: Priority 1, feature enhancement

#960 Refactor dashboard page components into modules
  src/components/ChannelInfo.tsx
  src/modules/channelDashboard/ChannelOwnerDashboard.tsx
  src/modules/channelDashboard/channelDashboardModule.tsx
  src/modules/createChannel/CreateChannelModule.js
  src/modules/createChannel/createChannel.css
  yarn.lock
Labels: Priority-2

#1001 Bug browser image upload issues
  package.json
  src/components/UploadLogo.jsx
  src/primaries/ImageClipper.js
  yarn.lock
Labels: Priority 1

#1000 rearranged wallets for mobile view
  src/AppLogin.tsx
  src/helpers/UtilityHelper.ts
Labels: Priority 1

#1009 Updated the warning on the dApp start
  src/AppLogin.tsx
Labels: documentation, Priority-2
