Repository push-protocol/push-dapp, pull requests merged in 2024-05, with the labels that each got.

#1562 PR template added
  .github/pull_request_template.md
Labels: Quick PR

#1574 Delegate wallet display on alias chain
  src/components/ChannelDetails.jsx
Labels: Quick PR

#1581 Chat reactions
  package.json
  src/components/InitState.tsx
  src/components/ViewDelegateeItem.jsx
  src/hooks/useResolveWeb3Name.ts
  src/modules/chat/ChatModule.tsx
  src/modules/inbox/InboxModule.tsx
  src/sections/chat/ChatSection.tsx
  src/singletons/ChannelsDataStore.js
  src/structure/MasterInterfacePage.tsx
  yarn.lock
Labels: ui enhancement, feature enhancement

#1584 🐛 [BUG] - [BUMP SDK IN DAPP] Skeleton loading in dark mode appears like light mode in chat
  package.json
  yarn.lock
Labels: bug, Quick PR, DO NOT MERGE

#1578 Space id integration
  package.json
  src/hooks/useResolveWeb3Name.ts
  yarn.lock
Labels: Quick PR, DO NOT MERGE

#1588 Fixed the chatPreview list to chatview error
  src/modules/chat/ChatModule.tsx
Labels: Quick PR

#1593 DApp- BUMP-SDK-VERSION-TO-1.3.7
  package.json
  yarn.lock
Labels: Quick PR, DO NOT MERGE
