Repository push-protocol/push-dapp, pull requests merged in 2024-06, with the labels that each got.

#1595 [BUG] - [BUMP SDK IN DAPP] Group Info Modal UI issues
  package.json
  yarn.lock
Labels: DO NOT MERGE

#1615 DAPP-1614-NFT-Claim-Edit
  public/svg/AccessNFTText.svg
  public/svg/claim-galxe-banner.svg
  src/modules/claimGalxe/ClaimGalxeModule.tsx
Labels: Quick PR

#1617 Added gap and fixed padding/margin prop in the box component
  src/blocks/Blocks.types.ts
  src/blocks/Blocks.utils.ts
  src/blocks/box/Box.constants.ts
  src/blocks/box/Box.tsx
  src/blocks/box/Box.types.ts
  src/blocks/box/Box.utils.ts
Labels: Quick PR

#1624 DAPP-1598 fixed push snap modal icons
  src/components/PushSnap/SnapInformationModal.tsx
Labels: bug, Quick PR

#1663 Change the header message in galxe claim page
  src/modules/claimGalxe/ClaimGalxeModule.tsx
Labels: Quick PR

#1669 Update horizontal padding on DS Buttons
  src/blocks/button/Button.constants.ts
Labels: DApp - DS, Quick PR

#1635 DApp-1551 blocks/Tooltip
  package.json
  src/blocks/index.ts
  src/blocks/text/Text.constants.ts
  src/blocks/tooltip/Tooltip.constants.ts
  src/blocks/tooltip/Tooltip.tsx
  src/blocks/tooltip/Tooltip.types.ts
  src/blocks/tooltip/Tooltip.utils.ts
  src/blocks/tooltip/index.ts
  src/common/hooks/index.ts
  src/common/hooks/useIsVisible.ts
  yarn.lock
Labels: DApp - DS

#1637 Fix: Mobile Input bar on Chat
  src/App.tsx
  src/modules/chat/ChatModule.tsx
  src/structure/MasterInterfacePage.tsx
Labels: bug
