Repository push-protocol/push-dapp, pull requests merged in 2024-08, with the labels that each got.

#1789 DApp-1784 fixed the prod dapp option visibility in header
  src/primaries/Profile.tsx
Labels: bug, Quick PR

#1801 DS-Dapp Notification Component
  package.json
  src/App.tsx
  src/blocks/illustrations/components/RewardPoints.tsx
  src/blocks/illustrations/index.ts
  src/blocks/index.ts
  src/blocks/notification/Notification.tsx
  src/blocks/notification/Notification.types.ts
  src/blocks/notification/index.ts
  src/blocks/theme/colors/colors.semantics.ts
  src/blocks/theme/semantics/semantics.notifications.ts
  yarn.lock
Labels: DApp - DS

#1808 DApp-1807 updated prod nft whitelist file
  src/config/alphaAccessNft/whitelist.json
Labels: Quick PR

#1828 Create pagination component
  package.json
  src/blocks/icons/components/CaretLeft.tsx
  src/blocks/icons/components/CaretRight.tsx
  src/blocks/icons/index.ts
  src/blocks/index.ts
  src/blocks/pagination/Pagination.tsx
  src/blocks/pagination/Pagination.types.ts
  src/blocks/pagination/index.ts
  src/blocks/theme/colors/colors.semantics.ts
  src/blocks/theme/semantics/semantics.pagination.ts
  yarn.lock
Labels: DApp - DS
